name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - staging

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GKE_REGION }}
  CLUSTER_NAME: ${{ secrets.GKE_CLUSTER }}
  REGISTRY: us-central1-docker.pkg.dev

jobs:
  build-test-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- AUTH ----------
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker $REGISTRY --quiet

      # ---------- BUILD ----------
      - name: Build Backend Image
        run: |
          docker build -t $REGISTRY/$PROJECT_ID/apps/backend:${{ github.sha }} ./backend

      - name: Build Frontend Image
        run: |
          docker build -t $REGISTRY/$PROJECT_ID/apps/frontend:${{ github.sha }} ./frontend

      - name: Trivy scan backend image
        uses: aquasecurity/trivy-action@master
        env:
            IMAGE_REF: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/apps/backend:${{ github.sha }}
        with:
            image-ref: ${{ env.IMAGE_REF }}
            format: table
            severity: CRITICAL,HIGH
            # exit-code: 1
        
      # ---------- PUSH ----------
      - name: Push Images
        run: |
          docker push $REGISTRY/$PROJECT_ID/apps/backend:${{ github.sha }}
          docker push $REGISTRY/$PROJECT_ID/apps/frontend:${{ github.sha }}

      # ---------- DEPLOY ----------
      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION

      - name: Deploy to Kubernetes
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            NAMESPACE=production
          else
            NAMESPACE=staging
          fi

          sed -i "s|IMAGE_BACKEND|$REGISTRY/$PROJECT_ID/apps/backend:${{ github.sha }}|g" k8s/backend.yaml
          sed -i "s|IMAGE_FRONTEND|$REGISTRY/$PROJECT_ID/apps/frontend:${{ github.sha }}|g" k8s/frontend.yaml

          kubectl apply -f k8s/namespaces.yaml
          kubectl apply -n $NAMESPACE -f k8s/backend.yaml
          kubectl apply -n $NAMESPACE -f k8s/frontend.yaml
